# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ testingActions ]
  pull_request:
    branches: [ testingActions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  # Pulled directly from Matt Ball
  postman_tests: Newman Action
#    runs-on: ubuntu-latest
      # You may pin to the exact commit or the version.
      # uses: matt-ball/newman-action@fc6b86948918c445f34fade22874059806dc43fc
      uses: matt-ball/newman-action@0.0.28
      with:
        # Postman API key
        apiKey: # optional, default is postmanApiKey
        # Collection to use
        collection: # optional, default is postman_collection.json
        # Environment to use
        environment: # optional, default is postman_environment.json
        # Globals to use
        globals: # optional
        # Number of iterations to run on the collection
        iterationCount: # optional, default is 1
        # Path to CSV or JSON data file
        iterationData: # optional
        # Name/ID of folders to run instead of entire collection
        folder: # optional
        # Path to be used as working directory
        workingDir: # optional
        # Allow reading files outside of working directory
        insecureFileRead: # optional, default is true
        # Time to wait for the collection run to complete
        timeout: # optional, default is Infinity
        # Time to wait for scripts to return a response
        timeoutRequest: # optional, default is Infinity
        # Time to wait for scripts to return a response
        timeoutScript: # optional, default is Infinity
        # Time to wait between subsequent requests
        delayRequest: # optional, default is 0
        # Follow 3xx responses
        ignoreRedirects: # optional
        # Disable SSL verification and allow self-signed SSL
        insecure: # optional
        # Stop collection run gracefully on error
        bail: # optional
        # Always exit cleanly
        suppressExitCode: # optional
        # Reporter to use
        reporters: # optional, default is cli
        # Reporter options
        reporter: # optional
        # Modify colored CLI output
        color: # optional, default is auto
        # Path to public client certificate
        sslClientCert: # optional
        # Path to secret client key file
        sslClientKey: # optional
        # Secret client key passphrase
        sslClientPassphrase: # optional